* Block mart
A decentralized, ERC-721 based market place standard.
** Concept
Free yourself from the constraint's of centralized markets. This standard will give the opportunity for /anyone/ to buy, sell, and list items on an EVM blockchain. Trust is-built through existing mechanism's on the blockchain (Proof of humanity, tip transaction, etc).
** Standard
It's simple - dead simple.
A simple ERC721 token with JSON metadata hosted on IPFS (or where ever I don't give a crap)
#+begin_src javascript
{
    title: "Freedom",
    price: 0,
    desc: "what you gain when you decentralize your world",
    gpg_pub: "5DC056652A1C2C1A998EBB5FFA7FD7519088BD89",
    images: []
}
#+end_src


If something goes wrong the standard requires the use of status.im or the email in ENS meta data if available. No money flows through any "trusted" medium unless desired by the customer (e.i using some sort of escrow that sends an empty transaction with the metadata). Mediumes fir establishing trust already exist on the block chain, no need to reinvent the wheel or for you to trust more of my code than needed.

Simple, open, uncensorable

*We can probably add an optional, more robust trust system, I am open too any and all ideas*
** CLI usage
The CLI is responsible for generating the listing json and giving you an IPFS hash and eth commands (this will not run anything that can cost you money)

The cli has three modes for creating listings: 1 shot mode, pipe mode and interactive mode. 1 shot mode (-1) takes the standard argument format (discussed later) from the command arguments and spits out the generated ipfs hash, pipe(-p) mode reads it as lines of standard input, and interactive (-i) presents an interactive listing creation environment.

There is also a watch function that allows you to watch any address for incoming orders and filter out new orders (using a ~/.last_order_tx as a reference for the last opened order)

Some of us believe various forms of strong cryptography will cause the power of the state to decline, perhaps even collapse fairly abruptly. We believe the expansion into cyberspace, with secure communications, digital money, anonymity and pseudonymity, and other crypto-mediated interactions, will profoundly change the nature of economies and social interactions. Governments will have a hard time collecting taxes, regulating the behavior of individuals and corporations (small ones at least), and generally coercing folks when it can't even tell what continent folks are on! - Timothy C. May, crypto anarchist
